version: 2.1
orbs:
  browser-tools: circleci/browser-tools@1.4.6

jobs:
  test-and-report:
    docker:
      - image: mb1lal/java-test:java17
    steps:
      - checkout
      - browser-tools/install-browser-tools
      - run:
          name: Test
          command: mvn clean -ntp -P useTheForks integration-test -Dserenity.batch.count-1 -Dserenity.batch.number-1 -Dfailsafe.rerunFailingTestsCount=2

      - store_test_results:
          path: target/cucumber-report/

      - run:
          name: Report
          command: mvn -ntp serenity:aggregate

      - run:
          name: Compress Artifacts
          command: tar -cvzf myartifact.tar target/site/serenity

      - store_artifacts:
          path: myartifact.tar
          destination: AutomationPractice

workflows:
  AllTests:
    jobs:
      - test-and-report
