name: Java CI with Maven

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up JDK 21
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Run tests and generate report
        run: mvn clean -ntp verify -Dfailsafe.rerunFailingTestsCount=2

      - name: Upload report artifacts
        uses: actions/upload-artifact@v6
        with:
          name: serenity
          path: ./target/site/serenity
          if-no-files-found: error
          retention-days: 10

      - name: Create or checkout gh-pages branch (optional)
        continue-on-error: true
        run: git fetch origin gh-pages || git checkout -b gh-pages

      - name: Clean up gh-pages branch (optional)
        continue-on-error: true
        run: git rm -rf .

  deploy:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Download Build Artifact
        uses: actions/download-artifact@v7
        with:
          name: serenity
          path: ./serenity

      - name: Deploy report to Github Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v4
        with:
          PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: serenity
