name: Java CI with Maven

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Run tests
        run: |
             mvn clean -ntp -P useTheForks integration-test -Dfailsafe.rerunFailingTestsCount=2 -Dcucumber.filter.tags="@backend"  

      - name: Generate report
        run: |
              mvn -ntp serenity:aggregate

      - name: Upload report artifacts
        uses: actions/upload-artifact@v4.0.0
        with:
          name: serenity
          path: ./target/site/serenity
          if-no-files-found: error
          retention-days: 1

      - name: Create or checkout gh-pages branch
        continue-on-error: true
        run: |
            git fetch origin gh-pages || git checkout -b gh-pages

      - name: Clean up gh-pages branch
        run: |
            git rm -rf .
            git commit -m "Clean up gh-pages branch"
            git push origin gh-pages

  deploy:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Download Build Artifact
        uses: actions/download-artifact@v4.1.0
        with:
          name: serenity
          path: ./serenity

      - name: Deploy report to Github Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v3.9.3
        with:
          PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: serenity
