name: Java CI with Maven

on:
  push:
    branches: [ "Add-github-actions" ]
  pull_request:
    branches: [ "master" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Pull Docker image
        run: docker pull mb1lal/java-docker-image:java17

      - name: Start Docker container
        run: docker run -dt --entrypoint /bin/bash mb1lal/java-docker-image:java17

      - name: Run tests inside container
        run: mvn clean -ntp -P useTheForks integration-test -Dserenity.batch.count-1 -Dserenity.batch.number-1 -Dfailsafe.rerunFailingTestsCount=2