name: Java CI with Maven

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Run tests
        run: |
             mvn clean -ntp -P useTheForks integration-test -Dfailsafe.rerunFailingTestsCount=2"

      - name: Generate report
        run: |
              mvn serenity:aggregate
