name: Java CI with Maven

on:
  push:
    branches: [ "Add-github-actions" ]
  pull_request:
    branches: [ "master" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Pull Docker image
        run: docker pull mb1lal/java-docker-image:java17

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run tests inside Docker container
        run: |
            docker run --entrypoint /bin/bash -v ${{ github.workspace }}:/workspace mb1lal/java-docker-image:java17 -c "cd /workspace && firefox --version && chrome --version && google-chrome --version && mvn clean -ntp -P useTheForks integration-test -Dfailsafe.rerunFailingTestsCount=2 "